//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mcview.rc
//
#define IDC_ALARMLIST                   3
#define IDC_CHG_PWD                     3
#define IDC_ADD                         3
#define IDC_0                           3
#define IDC_ACKALARM                    4
#define IDC_RETURN_WND                  4
#define IDC_DELETE                      4
#define IDC_10                          4
#define IDC_INDEX                       5
#define IDC_PRINT                       5
#define IDC_PREVIOUS                    6
#define IDC_ACK                         6
#define IDC_ABOUT                       6
#define IDC_NEXT                        7
#define IDC_ACKALL                      7
#define IDC_KEY                         8
#define IDC_LOOP                        9
#define IDC_CLR                         17
#define IDC_1                           18
#define IDC_2                           19
#define IDC_3                           20
#define IDC_4                           21
#define IDC_5                           22
#define IDC_6                           24
#define IDC_7                           25
#define IDC_8                           26
#define IDC_9                           27
#define IDC_SUB                         28
#define IDC_DOT                         29
#define IDD_MCVIEW_DIALOG               102
#define IDD_FVIEW_DIALOG                106
#define IDR_MAINFRAME                   128
#define IDD_VIEW                        129
#define IDC_PUSH                        130
#define IDD_POPUP                       131
#define IDD_INPUT_D                     132
#define IDC_UPUSH                       133
#define IDI_NA                          136
#define IDD_INPUT_A                     138
#define IDD_ALARMLIST                   139
#define IDD_TREND_TIME                  140
#define IDD_SYSTEM                      142
#define IDD_PASSWORD                    143
#define IDD_ABOUT                       144
#define IDD_MCVIEW_DIALOG_S             148
#define IDD_TRENDCOMPS                  150
#define IDD_DNYTIP                      151
#define IDD_LOOP                        152
#define IDD_SELECT                      154
#define IDC_SYSTEM                      1000
#define IDC_TIME                        1005
#define IDC_NOW                         1005
#define IDC_ALARM                       1006
#define IDC_ERROR                       1008
#define IDC_SET                         1009
#define IDC_RESET                       1010
#define IDC_STATUS                      1011
#define IDC_VALUE                       1012
#define IDC_OUTPUT                      1013
#define IDC_LIMIT_MAX                   1014
#define IDC_LIMIT_MIN                   1015
#define IDC_DATE                        1024
#define IDC_LENGTH                      1026
#define IDC_RANK0                       1027
#define IDC_RANK1                       1028
#define IDC_RANK2                       1029
#define IDC_RANK3                       1030
#define IDC_RANK4                       1031
#define IDC_RANK5                       1032
#define IDC_RANK6                       1033
#define IDC_RANK7                       1034
#define IDC_RANK8                       1035
#define IDC_RANK9                       1036
#define IDC_PWD                         1037
#define IDC_RANK10                      1037
#define IDC_ERR                         1038
#define IDC_NEW_PWD                     1038
#define IDC_CFM_PWD                     1040
#define IDC_NOSWITCH                    1043
#define IDC_SW2                         1046
#define IDC_TAG1                        1047
#define IDC_CA1                         1048
#define IDC_MIN1                        1049
#define IDC_MAX1                        1050
#define IDC_TAG2                        1051
#define IDC_CA2                         1052
#define IDC_MIN2                        1053
#define IDC_MAX2                        1054
#define IDC_TAG3                        1055
#define IDC_CA3                         1056
#define IDC_MIN3                        1057
#define IDC_MAX3                        1058
#define IDC_TAG4                        1059
#define IDC_CA4                         1060
#define IDC_MIN4                        1061
#define IDC_MAX4                        1062
#define IDC_TAG5                        1063
#define IDC_CA5                         1064
#define IDC_MIN5                        1065
#define IDC_MAX5                        1066
#define IDC_SAVE                        1067
#define IDC_LOAD                        1068
#define IDC_TAG6                        1069
#define IDC_OBJECTS                     1070
#define IDC_CA6                         1070
#define IDC_LINKS                       1071
#define IDC_MIN6                        1071
#define IDC_LOOPLIST                    1072
#define IDC_MAX6                        1072
#define IDC_TAG7                        1073
#define IDC_CA7                         1074
#define IDC_INTERVAL                    1075
#define IDC_MIN7                        1075
#define IDC_CHECK1                      1076
#define IDC_MAX7                        1076
#define IDC_TREND                       1077
#define IDC_TAG8                        1077
#define IDC_AUTO_SCALE                  1078
#define IDC_DEL                         1079
#define IDC_CA8                         1080
#define IDC_MIN8                        1081
#define IDC_MAX8                        1082
#define IDC_TAG9                        1083
#define IDC_CA9                         1084
#define IDC_MIN9                        1085
#define IDC_MAX9                        1086
#define IDC_TAG10                       1087
#define IDC_CA10                        1088
#define IDC_MIN10                       1089
#define IDC_MAX10                       1090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
